
CREATE TABLE [dbo].[AccountDetails](
	[AccountNo] [varchar](8) NOT NULL,
	[Status] [varchar](50) NULL,
	[ReasonForClosed] [varchar](max) NULL,
PRIMARY KEY CLUSTERED 
(
	[AccountNo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

